#services:
#  nginx:
#    build: dockers/nginx/.
#    container_name: nginx
#    ports:
#      - "80:80"
#  wordpress:
#    build: dockers/wordpress/.
#    container_name: wordpress-php
#    ports:
#      - "8080:80"

services:
  nginx:
    build: dockers/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
  wordpress:
    build: dockers/wordpress/.
    container_name: wordpress-php
    expose:
      - "9000"
    volumes:
      - ./web:/var/www/html
