services:
  nginx:
    build: dockers/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    networks:
      - docker_network
    restart: always
    env_file: .env
      
  wordpress:
    build: dockers/wordpress/.
    container_name: wordpress-php
    expose:
      - "9000"
    volumes:
      - web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - docker_network
    restart: always
    env_file: .env

  mariadb:
    build: dockers/mariadb/.
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - docker_network
    restart: always
    env_file: .env

networks:
  docker_network:
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES_PATH}/database
  web:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES_PATH}/web
