server {
	#ipv4(32 bits, 4 octets x 8 bits) & ipv6(128 bits)
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name esellier.42.fr;

	#security protocol
	ssl_protocols TLSv1.3;
	
	#SSL key and certificate
	ssl_certificate     /etc/ssl/certs/inception.crt;
	ssl_certificate_key /etc/ssl/private/inception.key;
	
	root

	index

	location / {

	}

	location .... {

	}


}
